[workspace]
members = [
    "crates/forge-core",
    "crates/forge-py",
    "crates/forge-cli",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "BSD-3-Clause"
authors = ["BuildByNexora"]
repository = "https://github.com/BuildByNexora/Forge"

[workspace.dependencies]
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4", features = ["derive", "env"] }
fs2 = "0.4"
forge-core = { path = "crates/forge-core" }
pyo3 = { version = "0.22", features = ["extension-module"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
thiserror = "1"
uuid = { version = "1", features = ["v4"] }
